### ISSUE TITLE
[Help needed] Problem opening project

### ISSUE THREAD

**Issue by TehStoneMan** [neoforged/MDK#50]
I am trying to get started with NeoForge in order to update my mods, but I keep getting the following errors in Eclipse:
```
Archive for required library: 'D:/Minecraft Dev/MDK/.gradle/repositories/ng_dummy_ng/net/minecraft/client/1.20.4/client-1.20.4-client-extra.jar' in project 'MDK' cannot be read or is not a valid ZIP file
Archive for required library: 'D:/Minecraft Dev/MDK/.gradle/repositories/ng_dummy_ng/net/neoforged/neoforge/20.4.170/neoforge-20.4.170.jar' in project 'MDK' cannot be read or is not a valid ZIP file
Archive for required library: 'D:/Minecraft Dev/MDK/.gradle/repositories/ng_dummy_ng/net/neoforged/neoforge/20.4.170/neoforge-20.4.170.jar' in project 'MDK' cannot be read or is not a valid ZIP file
Build path contains duplicate entry: 'D:Minecraft Dev/MDK/.gradle/repositories/ng_dummy_ng/net/neoforged/neoforge/20.4.170/neoforge-20.4.170.jar' for project 'MDK'
The project cannot be built until build path errors are resolved
```
The problem files are 0 sized .jar files.
I have updated gradle, refreshed dependencies, cleaned and rerun the Eclipse tasks, even manually deleted these files, but they just keep returning.

**Comment by tmvkrpxl0** [comment]
Could you try updating to latest NeoGradle? It's 7.0.138 as of now.
If you still have other issues, please contact us in NeoGradle discord in relevant support channel.

**Comment by Shadows-of-Fire** [comment]
This issue should be resolved with the latest NG version.

**Comment by ewewukek** [comment]
problem persists in NG 7.0.157
neoforge-21.0.151-sources.jar is not empty but doesn't contain any source files.
as result no sources attached to Minecraft and NeoForge classes in generated Eclipse project
